import type { IconType } from 'react-icons'
import {
  SiFastapi,
  SiFigma,
  SiFirebase,
  SiGit,
  SiGooglecloud,
  SiGooglegemini,
  SiJavascript,
  SiLaravel,
  SiMysql,
  SiNextdotjs,
  SiNodedotjs,
  SiPhp,
  SiPostgresql,
  SiPython,
  SiReact,
  SiReactquery,
  SiRedis,
  SiRust,
  SiScikitlearn,
  SiSolana,
  SiSolidity,
  SiSpringboot,
  SiStellar,
  SiSui,
  SiSupabase,
  SiTailwindcss,
  SiThreedotjs,
  SiTypescript,
  SiVite,
} from 'react-icons/si'

export type StackItem = { name: string; icon: IconType; group: 'Frontend' | 'Backend' | 'Web3' | 'Tools' }

export const stack: StackItem[] = [
  { name: 'TypeScript', icon: SiTypescript, group: 'Frontend' },
  { name: 'JavaScript', icon: SiJavascript, group: 'Frontend' },
  { name: 'React', icon: SiReact, group: 'Frontend' },
  { name: 'Next.js', icon: SiNextdotjs, group: 'Frontend' },
  { name: 'Tailwind CSS', icon: SiTailwindcss, group: 'Frontend' },
  { name: 'Three.js', icon: SiThreedotjs, group: 'Frontend' },
  { name: 'React Query', icon: SiReactquery, group: 'Frontend' },
  { name: 'Vite', icon: SiVite, group: 'Frontend' },
  { name: 'Supabase', icon: SiSupabase, group: 'Backend' },
  { name: 'PostgreSQL', icon: SiPostgresql, group: 'Backend' },
  { name: 'Node.js', icon: SiNodedotjs, group: 'Backend' },
  { name: 'Firebase', icon: SiFirebase, group: 'Backend' },
  { name: 'Laravel', icon: SiLaravel, group: 'Backend' },
  { name: 'PHP', icon: SiPhp, group: 'Backend' },
  { name: 'Python', icon: SiPython, group: 'Backend' },
  { name: 'FastAPI', icon: SiFastapi, group: 'Backend' },
  { name: 'Spring Boot', icon: SiSpringboot, group: 'Backend' },
  { name: 'MySQL', icon: SiMysql, group: 'Backend' },
  { name: 'Redis', icon: SiRedis, group: 'Backend' },
  { name: 'scikit-learn', icon: SiScikitlearn, group: 'Backend' },
  { name: 'Solidity', icon: SiSolidity, group: 'Web3' },
  { name: 'Solana', icon: SiSolana, group: 'Web3' },
  { name: 'Sui', icon: SiSui, group: 'Web3' },
  { name: 'Stellar', icon: SiStellar, group: 'Web3' },
  { name: 'Rust', icon: SiRust, group: 'Web3' },
  { name: 'Figma', icon: SiFigma, group: 'Tools' },
  { name: 'Git', icon: SiGit, group: 'Tools' },
  { name: 'Google Cloud', icon: SiGooglecloud, group: 'Tools' },
  { name: 'Gemini', icon: SiGooglegemini, group: 'Tools' },
]
